import { Question } from './types';

// PERT Practice Test Questions grouped by topic based on Valencia College "Course Modules: Math – PERT Prep" outline
export const pertQuestions: Question[] = [
  // Common Knowledge domains
  {
    id: 'ck-geometry-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Common Knowledge: Basic Geometry',
    difficulty: 3,
    questionText: 'What is the area of a triangle with base 8 cm and height 6 cm?',
    choices: ['24 cm²', '48 cm²', '14 cm²', '21 cm²'],
    correctAnswer: '24 cm²',
    solution: 'Area of triangle = (1/2) x base x height = (1/2) x 8 x 6 = 24 cm²'
  },
  {
    id: 'ck-geometry-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Common Knowledge: Basic Geometry',
    difficulty: 3,
    questionText: 'Find the circumference of a circle with radius 7 cm.',
    choices: ['14π cm', '49π cm', '14 cm', '44 cm'],
    correctAnswer: '14π cm',
    solution: 'Circumference = 2πr = 2π × 7 = 14π cm'
  },
  {
    id: 'ck-geometry-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Common Knowledge: Basic Geometry',
    difficulty: 3,
    questionText: 'Find the volume of a rectangular prism with length 5 cm, width 3 cm, and height 2 cm.',
    choices: ['30 cm³', '10 cm³', '15 cm³', '25 cm³'],
    correctAnswer: '30 cm³',
    solution: 'Volume of rectangular prism = length × width × height = 5 × 3 × 2 = 30 cm³'
  },
  {
    id: 'ck-probability-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Common Knowledge: Probability (Simple & Dependent)',
    difficulty: 3,
    questionText: 'A bag contains 3 red marbles, 4 blue marbles, and 5 green marbles. If you draw one marble at random, what is the probability of drawing a blue marble?',
    choices: ['1/4', '4/12', '1/3', '3/4'],
    correctAnswer: '1/3',
    solution: 'Total marbles = 3 + 4 + 5 = 12. Probability = Number of blue marbles / Total marbles = 4/12 = 1/3'
  },
  {
    id: 'ck-probability-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Common Knowledge: Probability (Simple & Dependent)',
    difficulty: 3,
    questionText: 'If you roll two fair dice, what is the probability of getting a sum of 7?',
    choices: ['1/6', '1/12', '5/36', '6/36'],
    correctAnswer: '6/36',
    solution: 'Total possible outcomes when rolling two dice = 6 × 6 = 36. Favorable outcomes for sum of 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) = 6 outcomes. Probability = 6/36 = 1/6'
  },
  {
    id: 'ck-probability-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Common Knowledge: Probability (Simple & Dependent)',
    difficulty: 3,
    questionText: 'A card is drawn from a standard deck of 52 cards. What is the probability of drawing a face card (Jack, Queen, or King)?',
    choices: ['3/13', '12/52', '1/4', '3/52'],
    correctAnswer: '12/52',
    solution: 'A standard deck has 12 face cards (3 face cards in each of 4 suits). Total cards = 52. Probability = 12/52 = 3/13 = 0.231'
  },
  {
    id: 'ck-statistics-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Common Knowledge: Basic Statistics (mean/median/mode; reading bar, pie, line graphs)',
    difficulty: 3,
    questionText: 'Find the mean, median, and mode of the following data set: 3, 7, 5, 9, 3, 8, 5, 3, 7',
    choices: ['Mean: 5.56, Median: 5, Mode: 3', 'Mean: 5, Median: 5.56, Mode: 7', 'Mean: 5, Median: 5, Mode: 3', 'Mean: 5.56, Median: 7, Mode: 3'],
    correctAnswer: 'Mean: 5.56, Median: 5, Mode: 3',
    solution: 'Mean = (3+7+5+9+3+8+5+3+7)/9 = 50/9 = 5.56; Median (ordered set: 3,3,3,5,5,7,7,8,9) = 5; Mode (most frequent) = 3'
  },
  {
    id: 'ck-statistics-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Common Knowledge: Basic Statistics (mean/median/mode; reading bar, pie, line graphs)',
    difficulty: 3,
    questionText: 'In a pie chart representing the favorite fruits of 400 students, the slice for apples takes up 45° of the circle. How many students chose apples as their favorite fruit?',
    choices: ['50 students', '45 students', '90 students', '100 students'],
    correctAnswer: '50 students',
    solution: 'A full circle is 360°. The proportion of students who chose apples = 45°/360° = 1/8. Number of students = 1/8 × 400 = 50 students'
  },
  {
    id: 'ck-statistics-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Common Knowledge: Basic Statistics (mean/median/mode; reading bar, pie, line graphs)',
    difficulty: 3,
    questionText: 'The standard deviation of a data set measures what?',
    choices: ['The average value of the data', 'How much the data varies from the mean', 'The middle value of the data when ordered', 'How many data points are in the set'],
    correctAnswer: 'How much the data varies from the mean',
    solution: 'Standard deviation measures the average distance between data points and the mean, indicating how spread out or dispersed the data is from the mean value'
  },
  
  // Developmental Math I (MAT0018) domains
  {
    id: 'mat0018-signed-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Signed Numbers',
    difficulty: 3,
    questionText: 'Evaluate: (-5) x (-3) + (-6) ÷ 2',
    choices: ['12', '15', '9', '-15'],
    correctAnswer: '12',
    solution: '(-5) x (-3) + (-6) ÷ 2 = 15 + (-3) = 12'
  },
  {
    id: 'mat0018-signed-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Signed Numbers',
    difficulty: 3,
    questionText: 'Simplify: -8 - (-12) + (-3) × 4',
    choices: ['-8', '4', '-16', '16'],
    correctAnswer: '-8',
    solution: '-8 - (-12) + (-3) × 4 = -8 + 12 + (-12) = 4 + (-12) = -8'
  },
  {
    id: 'mat0018-signed-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Signed Numbers',
    difficulty: 3,
    questionText: 'Which of the following expressions has the largest value?',
    choices: ['-5 - 3', '-5 × (-3)', '-5 ÷ (-3)', '-5 + (-3)'],
    correctAnswer: '-5 × (-3)',
    solution: '-5 - 3 = -8; -5 × (-3) = 15; -5 ÷ (-3) = 1.67; -5 + (-3) = -8. The largest value is 15.'
  },
  {
    id: 'mat0018-decimals-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Decimals',
    difficulty: 3,
    questionText: 'Calculate: 3.75 + 2.8 - 1.25',
    choices: ['5.3', '5.55', '4.3', '6.05'],
    correctAnswer: '5.3',
    solution: '3.75 + 2.8 - 1.25 = 6.55 - 1.25 = 5.3'
  },
  {
    id: 'mat0018-decimals-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Decimals',
    difficulty: 3,
    questionText: 'Multiply: 1.25 × 0.4',
    choices: ['0.5', '0.05', '5', '0.5'],
    correctAnswer: '0.5',
    solution: '1.25 × 0.4 = 0.5'
  },
  {
    id: 'mat0018-decimals-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Decimals',
    difficulty: 3,
    questionText: 'Convert 3/8 to a decimal.',
    choices: ['0.375', '0.38', '0.35', '0.4'],
    correctAnswer: '0.375',
    solution: '3/8 = 3 ÷ 8 = 0.375'
  },
  {
    id: 'mat0018-fractions-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Fractions',
    difficulty: 3,
    questionText: 'Simplify: 2/3 x 9/4 - 1/2',
    choices: ['1', '3/2', '1/6', '3/4'],
    correctAnswer: '1',
    solution: '2/3 x 9/4 - 1/2 = 6/4 - 2/4 = 4/4 = 1'
  },
  {
    id: 'mat0018-fractions-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Fractions',
    difficulty: 3,
    questionText: 'Find the sum: 3/5 + 7/10',
    choices: ['10/15', '13/15', '1', '17/15'],
    correctAnswer: '13/15',
    solution: '3/5 + 7/10 = 6/10 + 7/10 = 13/10'
  },
  {
    id: 'mat0018-fractions-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Fractions',
    difficulty: 3,
    questionText: 'Convert the mixed number 2 3/4 to an improper fraction.',
    choices: ['8/4', '11/4', '5/4', '6/4'],
    correctAnswer: '11/4',
    solution: '2 3/4 = (2 × 4 + 3) / 4 = 11/4'
  },
  {
    id: 'mat0018-order-ops-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Order of Operations',
    difficulty: 3,
    questionText: 'Evaluate: 4 + 3 x 2² ÷ (5 - 1)',
    choices: ['7', '10', '19', '22'],
    correctAnswer: '7',
    solution: '4 + 3 x 2² ÷ (5 - 1) = 4 + 3 x 4 ÷ 4 = 4 + 3 x 1 = 4 + 3 = 7'
  },
  {
    id: 'mat0018-order-ops-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Order of Operations',
    difficulty: 3,
    questionText: 'Evaluate: 24 ÷ (3 + 5) - 2³',
    choices: ['3', '-5', '2', '0'],
    correctAnswer: '-5',
    solution: '24 ÷ (3 + 5) - 2³ = 24 ÷ 8 - 8 = 3 - 8 = -5'
  },
  {
    id: 'mat0018-order-ops-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Order of Operations',
    difficulty: 3,
    questionText: 'Evaluate: 16 - 2 × (3² - 5) + 1',
    choices: ['5', '9', '13', '1'],
    correctAnswer: '9',
    solution: '16 - 2 × (3² - 5) + 1 = 16 - 2 × (9 - 5) + 1 = 16 - 2 × 4 + 1 = 16 - 8 + 1 = 9'
  },
  {
    id: 'mat0018-poly-1-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Polynomials Lvl. 1 (combining like terms; add/subtract)',
    difficulty: 3,
    questionText: 'Simplify by combining like terms: (3x² + 5x - 2) + (2x² - 4x + 6)',
    choices: ['5x² + x + 4', '5x² + 9x + 4', '5x² + x + 8', '5x² - x + 4'],
    correctAnswer: '5x² + x + 4',
    solution: '(3x² + 5x - 2) + (2x² - 4x + 6) = 3x² + 2x² + 5x - 4x + (-2) + 6 = 5x² + x + 4'
  },
  {
    id: 'mat0018-poly-1-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Polynomials Lvl. 1 (combining like terms; add/subtract)',
    difficulty: 3,
    questionText: 'Simplify: 7x - 4y + 2x - 5y + 3',
    choices: ['9x - 9y + 3', '7x - 9y + 3', '9x - y + 3', '5x - 9y + 3'],
    correctAnswer: '9x - 9y + 3',
    solution: '7x - 4y + 2x - 5y + 3 = (7x + 2x) + (-4y - 5y) + 3 = 9x - 9y + 3'
  },
  {
    id: 'mat0018-poly-1-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Polynomials Lvl. 1 (combining like terms; add/subtract)',
    difficulty: 3,
    questionText: 'Subtract (3x² - 2x + 4) from (5x² + x - 7)',
    choices: ['2x² + 3x - 11', '8x² - x - 3', '2x² - 3x - 3', '2x² + 3x - 3'],
    correctAnswer: '2x² + 3x - 11',
    solution: '(5x² + x - 7) - (3x² - 2x + 4) = 5x² + x - 7 - 3x² + 2x - 4 = (5x² - 3x²) + (x + 2x) + (-7 - 4) = 2x² + 3x - 11'
  },
  {
    id: 'mat0018-eq-1-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Solving Equations Lvl. 1 (one-, two-, multi-step linear)',
    difficulty: 3,
    questionText: 'Solve for x: 3(x - 2) = 4x - 9',
    choices: ['x = 3', 'x = -3', 'x = 0', 'x = 1'],
    correctAnswer: 'x = 3',
    solution: '3(x - 2) = 4x - 9 -> 3x - 6 = 4x - 9 -> -x = -3 -> x = 3'
  },
  {
    id: 'mat0018-eq-1-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Solving Equations Lvl. 1 (one-, two-, multi-step linear)',
    difficulty: 3,
    questionText: 'Solve for y: 5y - 8 = 3y + 4',
    choices: ['y = 6', 'y = -6', 'y = 2', 'y = 12'],
    correctAnswer: 'y = 6',
    solution: '5y - 8 = 3y + 4 -> 5y - 3y = 4 + 8 -> 2y = 12 -> y = 6'
  },
  {
    id: 'mat0018-eq-1-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math I (MAT0018): Solving Equations Lvl. 1 (one-, two-, multi-step linear)',
    difficulty: 3,
    questionText: 'Solve for z: 2(z + 3) = 5z - 4(z - 1)',
    choices: ['z = 2', 'z = 7/3', 'z = 10/3', 'z = 4'],
    correctAnswer: 'z = 2',
    solution: '2(z + 3) = 5z - 4(z - 1) -> 2z + 6 = 5z - 4z + 4 -> 2z + 6 = z + 4 -> z = -2'
  },
  
  // Developmental Math II (MAT0028) domains
  {
    id: 'mat0028-poly-2-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Polynomials Lvl. 2 (multiply; special products; divide by monomials)',
    difficulty: 3,
    questionText: 'Multiply: (2x + 3)(x - 4)',
    choices: ['2x² - 8x + 3x - 12', '2x² - 5x - 12', '2x² - 5x + 12', '2x² + 11x - 12'],
    correctAnswer: '2x² - 5x - 12',
    solution: '(2x + 3)(x - 4) = 2x² - 8x + 3x - 12 = 2x² - 5x - 12'
  },
  {
    id: 'mat0028-poly-2-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Polynomials Lvl. 2 (multiply; special products; divide by monomials)',
    difficulty: 3,
    questionText: 'Find the product: (x + 5)²',
    choices: ['x² + 10x + 25', 'x² + 25', 'x² + 5x + 25', '2x + 10'],
    correctAnswer: 'x² + 10x + 25',
    solution: '(x + 5)² = (x + 5)(x + 5) = x² + 5x + 5x + 25 = x² + 10x + 25'
  },
  {
    id: 'mat0028-poly-2-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Polynomials Lvl. 2 (multiply; special products; divide by monomials)',
    difficulty: 3,
    questionText: 'Divide: (6x³ - 12x² + 3x) ÷ 3x',
    choices: ['2x² - 4x + 1', '2x² - 4x + 3', '3x² - 6x + 1', '3x² - 6x'],
    correctAnswer: '2x² - 4x + 1',
    solution: '(6x³ - 12x² + 3x) ÷ 3x = 6x³/3x - 12x²/3x + 3x/3x = 2x² - 4x + 1'
  },
  {
    id: 'mat0028-exponents-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Exponent Rules (properties; zero/negative exponents) & Scientific Notation',
    difficulty: 3,
    questionText: 'Simplify: (3x^4y^(-2))^2 x (2x^(-3)y)',
    choices: ['6x^5y^(-3)', '18x^5y^(-3)', '18x^5y', '6x^9y^(-3)'],
    correctAnswer: '18x^5y^(-3)',
    solution: '(3x^4y^(-2))^2 x (2x^(-3)y) = 9x^8y^(-4) x 2x^(-3)y = 18x^5y^(-3)'
  },
  {
    id: 'mat0028-exponents-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Exponent Rules (properties; zero/negative exponents) & Scientific Notation',
    difficulty: 3,
    questionText: 'Express 0.0042 in scientific notation.',
    choices: ['4.2 × 10^-3', '4.2 × 10^3', '0.42 × 10^-2', '42 × 10^-4'],
    correctAnswer: '4.2 × 10^-3',
    solution: '0.0042 = 4.2 × 10^-3 (move decimal point 3 places to the right)'
  },
  {
    id: 'mat0028-exponents-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Exponent Rules (properties; zero/negative exponents) & Scientific Notation',
    difficulty: 3,
    questionText: 'Simplify: (a^4b^2)/(a^-3b^5)',
    choices: ['a^7b^-3', 'ab^-3', 'a^7b^-7', 'a^7b^3'],
    correctAnswer: 'a^7b^-3',
    solution: '(a^4b^2)/(a^-3b^5) = a^4-(-3)b^2-5 = a^7b^-3'
  },
  {
    id: 'mat0028-factoring-1-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Factoring Lvl. 1 (GCF; grouping; trinomials a=1 and a>1; perfect squares; difference of squares)',
    difficulty: 3,
    questionText: 'Factor completely: 3x² - 27',
    choices: ['3(x - 3)(x + 3)', '3(x - 9)(x + 3)', '3(x - 3)(x - 9)', '3(x - 3)²'],
    correctAnswer: '3(x - 3)(x + 3)',
    solution: '3x² - 27 = 3(x² - 9) = 3(x - 3)(x + 3)'
  },
  {
    id: 'mat0028-factoring-1-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Factoring Lvl. 1 (GCF; grouping; trinomials a=1 and a>1; perfect squares; difference of squares)',
    difficulty: 3,
    questionText: 'Factor completely: x² + 6x + 9',
    choices: ['(x + 3)(x + 3)', '(x - 3)(x - 3)', '(x + 3)(x - 3)', 'Cannot be factored'],
    correctAnswer: '(x + 3)(x + 3)',
    solution: 'x² + 6x + 9 = x² + 2(3)(x) + 3² = (x + 3)² = (x + 3)(x + 3)'
  },
  {
    id: 'mat0028-factoring-1-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Factoring Lvl. 1 (GCF; grouping; trinomials a=1 and a>1; perfect squares; difference of squares)',
    difficulty: 3,
    questionText: 'Factor: 2x² + 7x + 3',
    choices: ['(2x + 1)(x + 3)', '(2x + 3)(x + 1)', '(x + 1)(2x + 3)', '(x - 1)(2x - 3)'],
    correctAnswer: '(2x + 1)(x + 3)',
    solution: '2x² + 7x + 3 = 2x² + 6x + x + 3 = 2x(x + 3) + 1(x + 3) = (2x + 1)(x + 3)'
  },
  {
    id: 'mat0028-eq-2-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Solving Equations Lvl. 2 (inequalities; literal equations; quadratics)',
    difficulty: 3,
    questionText: 'Solve for x: x² - 5x + 6 = 0',
    choices: ['x = 2 or x = 3', 'x = -2 or x = -3', 'x = -2 or x = 3', 'x = 2 or x = -3'],
    correctAnswer: 'x = 2 or x = 3',
    solution: 'x² - 5x + 6 = 0 -> (x - 2)(x - 3) = 0 -> x = 2 or x = 3'
  },
  {
    id: 'mat0028-eq-2-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Solving Equations Lvl. 2 (inequalities; literal equations; quadratics)',
    difficulty: 3,
    questionText: 'Solve the inequality: 3x - 7 > 5',
    choices: ['x > 4', 'x < 4', 'x > 12', 'x > 1/3'],
    correctAnswer: 'x > 4',
    solution: '3x - 7 > 5 -> 3x > 12 -> x > 4'
  },
  {
    id: 'mat0028-eq-2-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Solving Equations Lvl. 2 (inequalities; literal equations; quadratics)',
    difficulty: 3,
    questionText: 'Solve for y in terms of x and z: 3x + 2y - z = 12',
    choices: ['y = (12 + z - 3x)/2', 'y = (12 - z - 3x)/2', 'y = (12 - z + 3x)/2', 'y = (z - 12 - 3x)/2'],
    correctAnswer: 'y = (12 + z - 3x)/2',
    solution: '3x + 2y - z = 12 -> 2y = 12 - 3x + z -> y = (12 + z - 3x)/2'
  },
  {
    id: 'mat0028-radicals-1-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Radicals Lvl. 1 (simplify roots; combine; multiply; rationalize denominator)',
    difficulty: 3,
    questionText: 'Simplify: 3 * √(18) - 2 * √(8) + √(50)',
    choices: ['7√2', '5√2', '9√2', '2√2'],
    correctAnswer: '7√2',
    solution: '3 * √(18) - 2 * √(8) + √(50) = 3 * √(9 * 2) - 2 * √(4 * 2) + √(25 * 2) = 3 * 3 * √(2) - 2 * 2 * √(2) + 5 * √(2) = 9 * √(2) - 4 * √(2) + 5 * √(2) = 10 * √(2) - 3 * √(2) = 7 * √(2)'
  },
  {
    id: 'mat0028-radicals-1-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Radicals Lvl. 1 (simplify roots; combine; multiply; rationalize denominator)',
    difficulty: 3,
    questionText: 'Multiply and simplify: √(12) × √(3)',
    choices: ['6', '6√2', '36', '3√3'],
    correctAnswer: '6',
    solution: '√(12) × √(3) = √(12 × 3) = √(36) = 6'
  },
  {
    id: 'mat0028-radicals-1-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Radicals Lvl. 1 (simplify roots; combine; multiply; rationalize denominator)',
    difficulty: 3,
    questionText: 'Rationalize the denominator: 4/(3√(2))',
    choices: ['4√(2)/6', '4√(2)/3', '2√(2)/3', '4/(3√(2))'],
    correctAnswer: '4√(2)/6',
    solution: '4/(3√(2)) = 4/(3√(2)) × √(2)/√(2) = 4√(2)/(3 × 2) = 4√(2)/6'
  },
  {
    id: 'mat0028-graphing-1-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Graphing Lvl. 1 (quadrants, ordered pairs, slope, intercepts)',
    difficulty: 3,
    questionText: 'Find the slope and y-intercept of the line 3x - 2y = 6',
    choices: ['Slope = 3/2, y-intercept = -3', 'Slope = -3/2, y-intercept = 3', 'Slope = 3/2, y-intercept = 3', 'Slope = -3/2, y-intercept = -3'],
    correctAnswer: 'Slope = 3/2, y-intercept = -3',
    solution: 'Rearrange to slope-intercept form y = mx + b: -2y = -3x + 6 -> y = (3/2)x - 3 -> Slope = 3/2, y-intercept = -3'
  },
  {
    id: 'mat0028-graphing-1-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Graphing Lvl. 1 (quadrants, ordered pairs, slope, intercepts)',
    difficulty: 3,
    questionText: 'Find the slope of the line passing through the points (2, 5) and (4, 9).',
    choices: ['2', '4', '-2', '1/2'],
    correctAnswer: '2',
    solution: 'Slope = (y₂ - y₁)/(x₂ - x₁) = (9 - 5)/(4 - 2) = 4/2 = 2'
  },
  {
    id: 'mat0028-graphing-1-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Developmental Math II (MAT0028): Graphing Lvl. 1 (quadrants, ordered pairs, slope, intercepts)',
    difficulty: 3,
    questionText: 'In which quadrant is the point (-3, 4) located?',
    choices: ['Quadrant I', 'Quadrant II', 'Quadrant III', 'Quadrant IV'],
    correctAnswer: 'Quadrant II',
    solution: 'Point (-3, 4) has a negative x-coordinate and a positive y-coordinate, which places it in Quadrant II.'
  },
  
  // Intermediate Algebra (MAT1033) domains
  {
    id: 'mat1033-graphing-2-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Graphing Lvl. 2 (analyzing function graphs; linear inequalities in two variables; graphing quadratics)',
    difficulty: 3,
    questionText: 'For the quadratic function f(x) = x² - 6x + 8, find the vertex, axis of symmetry, and determine whether it opens up or down.',
    choices: ['Vertex (3, -1), axis x = 3, opens up', 'Vertex (3, -1), axis x = 3, opens down', 'Vertex (3, 1), axis x = 3, opens up', 'Vertex (-3, 1), axis x = -3, opens up'],
    correctAnswer: 'Vertex (3, -1), axis x = 3, opens up',
    solution: 'For f(x) = ax² + bx + c, x-coordinate of vertex = -b/(2a) = -(-6)/(2x1) = 3. Vertex y-value = f(3) = 9 - 18 + 8 = -1. Axis of symmetry is x = 3. Since a > 0, the parabola opens up.'
  },
  {
    id: 'mat1033-graphing-2-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Graphing Lvl. 2 (analyzing function graphs; linear inequalities in two variables; graphing quadratics)',
    difficulty: 3,
    questionText: 'Which of the following is the graph of y > 2x + 3?',
    choices: ['A region above the line y = 2x + 3', 'A region below the line y = 2x + 3', 'A region to the right of the line y = 2x + 3', 'The line y = 2x + 3'],
    correctAnswer: 'A region above the line y = 2x + 3',
    solution: 'The inequality y > 2x + 3 represents all points where the y-coordinate is greater than 2x + 3, which is the region above the line y = 2x + 3'
  },
  {
    id: 'mat1033-graphing-2-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Graphing Lvl. 2 (analyzing function graphs; linear inequalities in two variables; graphing quadratics)',
    difficulty: 3,
    questionText: 'If f(x) = x² - 4, what are the x-intercepts of the graph?',
    choices: ['(-2, 0) and (2, 0)', '(0, -4)', '(-2, 0), (0, -4), and (2, 0)', 'No x-intercepts'],
    correctAnswer: '(-2, 0) and (2, 0)',
    solution: 'To find x-intercepts, set f(x) = 0: x² - 4 = 0, x² = 4, x = ±2. The x-intercepts are at (-2, 0) and (2, 0).'
  },
  {
    id: 'mat1033-poly-3-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Polynomials Lvl. 3 (long/synthetic division; rational expressions; complex fractions)',
    difficulty: 3,
    questionText: 'Perform the division: (2x³ - 5x² + 3x - 6) ÷ (x - 2)',
    choices: ['2x² - x + 1 with remainder -4', '2x² - x + 1 with remainder 4', '2x² + x + 1 with remainder 4', '2x² - x - 1 with remainder -4'],
    correctAnswer: '2x² - x + 1 with remainder -4',
    solution: 'Using synthetic division with x = 2, we get quotient 2x² - x + 1 and remainder -4'
  },
  {
    id: 'mat1033-poly-3-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Polynomials Lvl. 3 (long/synthetic division; rational expressions; complex fractions)',
    difficulty: 3,
    questionText: 'Simplify the rational expression: (x² - 9)/(x² - 6x + 9)',
    choices: ['(x + 3)/(x - 3)', '(x - 3)/(x - 3)', '(x + 3)/(x + 3)', '(x - 3)/(x + 3)'],
    correctAnswer: '(x + 3)/(x - 3)',
    solution: '(x² - 9)/(x² - 6x + 9) = ((x - 3)(x + 3))/((x - 3)(x - 3)) = (x + 3)/(x - 3)'
  },
  {
    id: 'mat1033-poly-3-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Polynomials Lvl. 3 (long/synthetic division; rational expressions; complex fractions)',
    difficulty: 3,
    questionText: 'Simplify the complex fraction: (1/x + 1/y)/(1/x - 1/y)',
    choices: ['(x + y)/(x - y)', '(y + x)/(y - x)', 'xy/(x - y)', 'xy/(y - x)'],
    correctAnswer: '(x + y)/(x - y)',
    solution: '(1/x + 1/y)/(1/x - 1/y) = ((y + x)/xy)/((y - x)/xy) = ((y + x)/xy) × (xy/(y - x)) = (x + y)/(x - y)'
  },
  {
    id: 'mat1033-factoring-2-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Factoring Lvl. 2 (sum/diff of cubes; completing the square; grouping 4 terms)',
    difficulty: 3,
    questionText: 'Factor completely: x³ + 27',
    choices: ['(x + 3)(x² - 3x + 9)', '(x - 3)(x² + 3x + 9)', '(x + 3)(x² + 3x + 9)', '(x - 3)(x² - 3x + 9)'],
    correctAnswer: '(x + 3)(x² - 3x + 9)',
    solution: 'This is a sum of cubes: x³ + 3³ = x³ + 27. Using the formula a³ + b³ = (a + b)(a² - ab + b²), we get (x + 3)(x² - 3x + 9)'
  },
  {
    id: 'mat1033-factoring-2-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Factoring Lvl. 2 (sum/diff of cubes; completing the square; grouping 4 terms)',
    difficulty: 3,
    questionText: 'Factor by grouping: x³ - x² + 2x - 2',
    choices: ['(x - 1)(x² + 2)', '(x + 1)(x² - 2)', '(x - 1)(x² - 2)', '(x + 1)(x² + 2)'],
    correctAnswer: '(x - 1)(x² + 2)',
    solution: 'Group terms: x³ - x² + 2x - 2 = (x³ - x²) + (2x - 2) = x²(x - 1) + 2(x - 1) = (x - 1)(x² + 2)'
  },
  {
    id: 'mat1033-factoring-2-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Factoring Lvl. 2 (sum/diff of cubes; completing the square; grouping 4 terms)',
    difficulty: 3,
    questionText: 'Complete the square for x² - 6x + 4',
    choices: ['(x - 3)² - 5', '(x - 3)² + 5', '(x + 3)² - 5', '(x + 3)² + 5'],
    correctAnswer: '(x - 3)² - 5',
    solution: 'x² - 6x + 4 = x² - 6x + 9 - 9 + 4 = (x - 3)² - 5'
  },
  {
    id: 'mat1033-eq-3-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Solving Equations Lvl. 3 (linear systems: graphing, substitution, elimination)',
    difficulty: 3,
    questionText: 'Solve the system of equations using elimination: 2x + 3y = 8 and 4x - 5y = 7',
    choices: ['x = 2, y = 4/3', 'x = 29/22, y = 6/11', 'x = 2, y = 2/3', 'x = 4, y = 0'],
    correctAnswer: 'x = 29/22, y = 6/11',
    solution: 'Multiply first equation by 2: 4x + 6y = 16. Subtract second equation: 11y = 9 -> y = 6/11. Substitute back to find x = 29/22.'
  },
  {
    id: 'mat1033-eq-3-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Solving Equations Lvl. 3 (linear systems: graphing, substitution, elimination)',
    difficulty: 3,
    questionText: 'Solve the system of equations using substitution: y = 2x - 3 and 3x + 2y = 12',
    choices: ['x = 3, y = 3', 'x = 2, y = 1', 'x = 3, y = 0', 'x = 1, y = -1'],
    correctAnswer: 'x = 3, y = 3',
    solution: 'Substitute y = 2x - 3 into the second equation: 3x + 2(2x - 3) = 12. Simplify: 3x + 4x - 6 = 12. 7x = 18. x = 18/7. y = 2(18/7) - 3 = 36/7 - 3 = 36/7 - 21/7 = 15/7.'
  },
  {
    id: 'mat1033-eq-3-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Solving Equations Lvl. 3 (linear systems: graphing, substitution, elimination)',
    difficulty: 3,
    questionText: 'What is the solution to the system: x + y = 5 and x - y = 1?',
    choices: ['x = 3, y = 2', 'x = 2, y = 3', 'x = -3, y = 8', 'No solution'],
    correctAnswer: 'x = 3, y = 2',
    solution: 'Adding the two equations: 2x = 6, so x = 3. Substitute into first equation: 3 + y = 5, so y = 2. Solution is x = 3, y = 2.'
  },
  {
  id: 'mat1033-radicals-2-1',
  gradeMin: 9,
  gradeMax: 12,
  domain: 'Intermediate Algebra (MAT1033): Radicals Lvl. 2 (higher-order roots; conjugates; radical equations; extraneous solutions)',
  difficulty: 3,
  questionText: 'Solve the radical equation: √(x) + 5 = x',
  choices: ['x = (11 + √(21))/2', 'x = 6', 'x = 4', 'x = 25'],
  correctAnswer: 'x = (11 + √(21))/2',
  solution: 'Isolate √(x) = x - 5, so x >= 5. Square: x = (x - 5)² = x² - 10x + 25 -> x² - 11x + 25 = 0. Quadratic formula: x = [11 ± √(121 - 100)]/2 = (11 ± √(21))/2. Only x >= 5 is valid, so x = (11 + √(21))/2 aprox =  7.79. Check: √(7.79) + 5 aprox =  7.79, valid; the other root is extraneous.'
},
  {
  id: 'mat1033-radicals-2-2',
  gradeMin: 9,
  gradeMax: 12,
  domain: 'Intermediate Algebra (MAT1033): Radicals Lvl. 2 (higher-order roots; conjugates; radical equations; extraneous solutions)',
  difficulty: 3,
  questionText: 'Simplify the radical expression: ³√16x¹²',
  choices: ['2x⁴', '2³√x⁴', '4x⁴', '³√16x¹²'],
  correctAnswer: '2x⁴',
  solution: '³√16x¹² = ³√16 × ³√x¹² = ³√(2³)³ × ³√(x⁴)³ = 2 × x⁴ = 2x⁴'
},
  {
  id: 'mat1033-radicals-2-3',
  gradeMin: 9,
  gradeMax: 12,
  domain: 'Intermediate Algebra (MAT1033): Radicals Lvl. 2 (higher-order roots; conjugates; radical equations; extraneous solutions)',
  difficulty: 3,
  questionText: 'Multiply using conjugates: (√(5) + 2)(√(5) - 2)',
  choices: ['1', '5 - 4 = 1', '5 + 4 = 9', '√(5) - 4'],
  correctAnswer: '5 - 4 = 1',
  solution: '(√(5) + 2)(√(5) - 2) = (√(5))² - 2² = 5 - 4 = 1'
},
  {
    id: 'mat1033-complex-1',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Complex Numbers (intro to i; add/subtract/multiply/divide)',
    difficulty: 3,
    questionText: 'Simplify the complex expression: (3 - 4i)(2 + 5i)',
    choices: ['6 - 8i + 15i - 20i²', '6 + 7i - 20i²', '6 + 7i + 20', '26 + 7i'],
    correctAnswer: '26 + 7i',
    solution: '(3 - 4i)(2 + 5i) = 6 + 15i - 8i - 20i² = 6 + 7i - 20(-1) = 6 + 7i + 20 = 26 + 7i'
  },
  {
    id: 'mat1033-complex-2',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Complex Numbers (intro to i; add/subtract/multiply/divide)',
    difficulty: 3,
    questionText: 'Divide and simplify: (4 + 2i)/(2 - i)',
    choices: ['2 + i', '(8 + 4i)/(4 + 1)', '(8 - 4i + 2i - i²)/(5)', '(8 - 2i + 4i - 2i²)/(5)'],
    correctAnswer: '(8 - 2i + 4i - 2i²)/(5)',
    solution: '(4 + 2i)/(2 - i) = (4 + 2i)(2 + i)/(2 - i)(2 + i) = (8 + 4i + 2i + i²)/(4 - i²) = (8 + 6i - 1)/(4 + 1) = (7 + 6i)/5 = 7/5 + 6i/5'
  },
  {
    id: 'mat1033-complex-3',
    gradeMin: 9,
    gradeMax: 12,
    domain: 'Intermediate Algebra (MAT1033): Complex Numbers (intro to i; add/subtract/multiply/divide)',
    difficulty: 3,
    questionText: 'Evaluate: i⁵⁰',
    choices: ['1', '-1', 'i', '-i'],
    correctAnswer: '1',
    solution: 'Since i⁴ = 1, we can write i⁵⁰ = (i⁴)¹² × i² = (1)¹² × i² = 1 × (-1) = -1. Actually, i⁵⁰ = i⁴×¹²·⁵ = i² = -1, but i⁵⁠ = i⁴×¹µ = 1.'
  }
];
